name: Confident Me
favicon: null
layout_spectrum: 0.5710370382294059
typography_spectrum: 0.7768836475443095
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.13631998165510595
  lightness: 0.8246670302469283
  saturation: 0.6799170393496752
  rhythmicContrast: 0.11923581012524664
purpose: []
